apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  annotations:
    linkerd.io/inject: enabled

---

apiVersion: v1
kind: Namespace
metadata:
  name: pingo-dev
  annotations:
    linkerd.io/inject: enabled