apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-processor
  labels:
    app: name-processor
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-processor 
  template:
    metadata:
      labels:
        app: name-processor
        version: v1
    spec:
      containers:
      - image: 4suredev/name-processor:v1
        # imagePullPolicy: Always
        name: name-processor
        ports:
        - name: name-processor
          containerPort: 3000