apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwa 
  template:
    metadata:
      labels:
        app: pwa
        version: v1
    spec:
      containers:
      - image: 4suredev/pingo-dev:v1
        imagePullPolicy: Always
        name: pwa
        ports:
        - name: pwa
          containerPort: 3000