apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - "pingo.dev.frontend.127.0.0.1.nip.io"
  gateways:
  - pingo-dev-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: frontend