apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 4suredev/pingo:1.1
        imagePullPolicy: Always
        name: frontend
        ports:
        - name: frontend
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_THEME_COLOR
          value: "#FFFFFF"
        - name: NEXT_PUBLIC_MANIEFST_PATH
          value: "/manifest.json"
        - name: NEXT_PUBLIC_ICON_192_PATH
          value: "/icons/icon192x192.png"
        - name: NEXT_PUBLIC_ICON_512_PATH
          value: "/icons/icon512x512.png"
        - name: NEXT_PUBLIC_FAV_ICON_PATH
          value: "/favicon.ico"
        - name: NEXT_PUBLIC_APP_NAME
          value: "PWA Base Project"
        - name: NEXT_PUBLIC_APP_DESCRIPTION
          value: "This is the PWA BASE project to use for PWA enabled apps"
        - name: NEXT_PUBLIC_API_URL
          value: "https://jsonplaceholder.typicode.com"