apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend-ingress
spec:
  virtualhost:
    fqdn: pingo.dev.frontend.127.0.0.1.nip.io
  routes:
    - conditions:
      - prefix: /
      services:
        - name: frontend
          port: 80